project:
  type: website
  output-dir: docs

website:
  title: "Reproducible Manuscripts in R with Quarto Workshop"
  sidebar:
    background: "maroon"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Workshop"
        contents:
          - href: index.qmd
            text: Home
          - section: "Slides"
            contents:
              - href: slides/introduction.qmd
                text: Introduction
              - href: slides/markdown-syntax.qmd
                text: Markdown
              - href: slides/Referencing.qmd
                text: Referencing
              - href: slides/code-chunks.qmd
                text: Analysis
              - href: slides/rendering.qmd
                text: Rendering
format:
  html:
    theme: superhero
    toc: true
    css: styles_bc.css
    fontsize: "20pt"

editor: visual

